import type { Product, Order } from './definitions';

export const products: Product[] = [
  {
    id: '1',
    name: 'Wireless Headphones',
    description: 'High-fidelity sound with noise cancellation. 30-hour battery life.',
    price: 199.99,
    imageUrl: 'https://picsum.photos/seed/1/600/400',
    imageHint: 'headphones technology',
    stock: 25,
    category: 'Electronics',
  },
  {
    id: '2',
    name: 'Leather Backpack',
    description: 'Stylish and durable backpack for work or travel. Fits a 15-inch laptop.',
    price: 120.0,
    imageUrl: 'https://picsum.photos/seed/2/600/400',
    imageHint: 'backpack fashion',
    stock: 15,
    category: 'Fashion',
  },
  {
    id: '3',
    name: 'Smart Watch',
    description: 'Track your fitness, notifications, and more. Waterproof design.',
    price: 249.5,
    imageUrl: 'https://picsum.photos/seed/3/600/400',
    imageHint: 'smartwatch technology',
    stock: 30,
    category: 'Electronics',
  },
  {
    id: '4',
    name: 'Organic Cotton T-Shirt',
    description: 'Soft, breathable, and ethically made. Available in various colors.',
    price: 25.0,
    imageUrl: 'https://picsum.photos/seed/4/600/400',
    imageHint: 't-shirt apparel',
    stock: 100,
    category: 'Apparel',
  },
  {
    id: '5',
    name: 'Ceramic Coffee Mug',
    description: 'A perfect 12oz mug for your morning coffee. Microwave and dishwasher safe.',
    price: 15.99,
    imageUrl: 'https://picsum.photos/seed/5/600/400',
    imageHint: 'mug kitchen',
    stock: 50,
    category: 'Home Goods',
  },
  {
    id: '6',
    name: 'Minimalist Desk Lamp',
    description: 'Modern LED desk lamp with adjustable brightness. Sleek aluminum design.',
    price: 79.0,
    imageUrl: 'https://picsum.photos/seed/6/600/400',
    imageHint: 'lamp home',
    stock: 20,
    category: 'Home Goods',
  },
  {
    id: '7',
    name: 'Bluetooth Speaker',
    description: 'Portable and waterproof with rich bass. 12-hour playtime.',
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/7/600/400',
    imageHint: 'speaker audio',
    stock: 40,
    category: 'Electronics',
  },
  {
    id: '8',
    name: 'Classic Sunglasses',
    description: 'Timeless style with 100% UV protection. Lightweight and comfortable.',
    price: 65.0,
    imageUrl: 'https://picsum.photos/seed/8/600/400',
    imageHint: 'sunglasses fashion',
    stock: 60,
    category: 'Fashion',
  },
  {
    id: '9',
    name: 'Insulated Water Bottle',
    description: 'Keeps drinks cold for 24 hours or hot for 12. 32oz capacity.',
    price: 35.0,
    imageUrl: 'https://picsum.photos/seed/9/600/400',
    imageHint: 'bottle lifestyle',
    stock: 80,
    category: 'Lifestyle',
  },
  {
    id: '10',
    name: 'Cozy Wool Blanket',
    description: 'Warm and soft, made from 100% merino wool. Perfect for chilly nights.',
    price: 150.0,
    imageUrl: 'https://picsum.photos/seed/10/600/400',
    imageHint: 'blanket home',
    stock: 18,
    category: 'Home Goods',
  },
  {
    id: '11',
    name: 'Gourmet Coffee Beans',
    description: 'Single-origin Ethiopian Yirgacheffe beans. Medium roast, 12oz bag.',
    price: 22.5,
    imageUrl: 'https://picsum.photos/seed/11/600/400',
    imageHint: 'coffee food',
    stock: 70,
    category: 'Food & Drink',
  },
  {
    id: '12',
    name: 'Hardcover Notebook',
    description: 'A5 dotted journal for notes and sketches. 160 pages of thick, high-quality paper.',
    price: 18.0,
    imageUrl: 'https://picsum.photos/seed/12/600/400',
    imageHint: 'notebook office',
    stock: 120,
    category: 'Office',
  },
];
